#!/bin/bash

### VPC NETS
#export OS_REGION_NAME=<os_region-name> # [GRA11, DE1, EU-SOUTH-MIL, EU-WEST-PAR]
#export VPC_REGION_NAME=<vpc_region-name> # [GRA, LIM, MIL, PAR]
#export VPC_NET_NAME=<vpc_region-name> # "pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# i.e. VPC_REGION_NAME=PAR
#export OS_REGION_NAME=EU-WEST-PAR
#export VPC_SEGMENT_NAME=<vpc_segment-name> # [LAN/GREEN, WAN/RED, DMZ/ORANGE, VPN/BLUE, CARP/PINK]
#export VPC_SEGMENT_ID=<vpc_vlan-id> # [2042, 2043, 2044, 2045, 2046]
#export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# i.e. VPC_REGION_NAME=GRA
#export OS_REGION_NAME=GRA11
#export VPC_SEGMENT_NAME=<vpc_segment-name> # [LAN/GREEN, WAN/RED, DMZ/ORANGE, VPN/BLUE, CARP/PINK]
#export VPC_SEGMENT_ID=<vpc_vlan-id> # [2062, 2063, 2064, 2065, 2066]
#export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"

# (EU) Parigi, Francia - EU-WEST-PAR (3AZ)
export OS_REGION_NAME=EU-WEST-PAR
export VPC_REGION_NAME=PAR
echo "DEPLOYING VPC opnsenseNETWORKs IN $VPC_REGION_NAME ..."
## VPC NET 1 - GREEN (LAN | 2042)
export VPC_SEGMENT_NAME=GREEN
export VPC_SEGMENT_ID=2042
export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
scripts/oscVPC-deployNetwork-par-GREEN.sh
echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
## VPC NET 2 - RED (WAN | 0)
export VPC_SEGMENT_NAME=RED
export VPC_SEGMENT_ID=0
export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
scripts/oscVPC-deployNetwork-par-RED.sh
echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
## VPC NET 3 - ORANGE (DMZ | 2044)
export VPC_SEGMENT_NAME=ORANGE
export VPC_SEGMENT_ID=2044
export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
scripts/oscVPC-deployNetwork-par-ORANGE.sh
echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
## VPC NET 4 - BLUE (VPN | 2045)
export VPC_SEGMENT_NAME=BLUE
export VPC_SEGMENT_ID=2045
export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
scripts/oscVPC-deployNetwork-par-BLUE.sh
echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
## VPC NET 5 - PINK (CARP | 2046)
export VPC_SEGMENT_NAME=PINK
export VPC_SEGMENT_ID=2046
export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
scripts/oscVPC-deployNetwork-par-PINK.sh
echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
echo "\!/ CHECK IF VPC opnsenseNETWORKs WERE DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

# # (EU) Milano, Italia - EU-SOUTH-MIL (3AZ)
# export OS_REGION_NAME=EU-SOUTH-MIL
# export VPC_REGION_NAME=MIL
# echo "DEPLOYING VPC opnsenseNETWORKs IN $VPC_REGION_NAME ..."
# ## VPC NET 1 - GREEN (LAN | 2052)
# export VPC_SEGMENT_NAME=GREEN
# export VPC_SEGMENT_ID=2052
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-par-GREEN.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# ## VPC NET 2 - RED (WAN | 0)
# export VPC_SEGMENT_NAME=RED
# export VPC_SEGMENT_ID=0
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-par-RED.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# echo "\!/ CHECK IF VPC opnsenseNETWORKs WERE DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

# # (EU) Gravelines, Francia - GRA11 (1AZ)
# export OS_REGION_NAME=GRA11
# export VPC_REGION_NAME=GRA
# echo "DEPLOYING VPC opnsenseNETWORKs IN $VPC_REGION_NAME ..."
# ## VPC NET 1 - GREEN (LAN | 2062)
# export VPC_SEGMENT_NAME=GREEN
# export VPC_SEGMENT_ID=2062
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-gra-GREEN.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# ## VPC NET 2 - RED (WAN | 0)
# export VPC_SEGMENT_NAME=RED
# export VPC_SEGMENT_ID=0
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-gra-RED.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# echo "\!/ CHECK IF VPC opnsenseNETWORKs WERE DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

# # (EU) Limburg, Germany - DE1 (1AZ)
# export OS_REGION_NAME=DE1
# export VPC_REGION_NAME=LIM
# echo "DEPLOYING VPC opnsenseNETWORKs IN $VPC_REGION_NAME ..."
# ## VPC NET 1 - GREEN (LAN | 2072)
# export VPC_SEGMENT_NAME=GREEN
# export VPC_SEGMENT_ID=2072
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-lim-GREEN.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# ## VPC NET 2 - RED (WAN | 0)
# export VPC_SEGMENT_NAME=RED
# export VPC_SEGMENT_ID=0
# export VPC_NET_NAME="pn-VPC_opnsense-$VPC_REGION_NAME-$VPC_SEGMENT_NAME-$VPC_SEGMENT_ID"
# echo "DEPLOYING VPC opnsense $VPC_SEGMENT_NAME segment as $VPC_SEGMENT_ID..."
# scripts/oscVPC-deployNetwork-lim-RED.sh
# echo "\!/ CHECK IF segment $VPC_SEGMENT_NAME WAS DEPLOYED IN $VPC_REGION_NAME as $VPC_SEGMENT_ID SUCCESSFUL \!/"
# echo "\!/ CHECK IF VPC opnsenseNETWORKs WERE DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"