#!/bin/bash

# Set OPN VM_IMAGE
# *ovh
OPN_ISO_IMAGE_VERSION=25.1 # 24.7.12|25.1|
OPN_ISO_IMAGE_ARCH=amd64 # amd64*|aarch64
OPN_ISO_IMAGE_CONSOLE=dvd # nano|dvd*|vga|serial
OPN_ISO_IMAGE_DISK_FORMAT=iso # iso*

# Set OPN ISO IMAGE URL
OPN_ISO_IMAGE_URL="https://pkg.opnsense.org/releases/$OPN_ISO_IMAGE_VERSION/OPNsense-$OPN_ISO_IMAGE_VERSION-$OPN_ISO_IMAGE_CONSOLE-$OPN_ISO_IMAGE_ARCH.$OPN_ISO_IMAGE_DISK_FORMAT.bz2"

# Set OPN TMP DIRECTORY vars
OPN_TMP_DIRECTORY=/tmp/opnsense-images
if [ ! -d "$OPN_TMP_DIRECTORY" ]; then
    #echo "$OPN_TMP_DIRECTORY does not exist."
    mkdir -p $OPN_TMP_DIRECTORY
fi

# Set OPN TMP FILE vars
OPN_TMP_FILE_BZ2=$OPN_TMP_DIRECTORY/OPNsense-$OPN_ISO_IMAGE_VERSION-$OPN_ISO_IMAGE_CONSOLE-$OPN_ISO_IMAGE_ARCH.$OPN_ISO_IMAGE_DISK_FORMAT.bz2

# Echo
echo "ECHO .> Downloading..."

# Get OPN VM IMAGE (BZ2)
time wget \
    -O $OPN_TMP_FILE_BZ2 \
    --no-check-certificate \
    $OPN_ISO_IMAGE_URL


# Echo
echo "ECHO .> $OPN_TMP_FILE_BZ2 Downloaded!"

# Extract OPN_TMP_FILE_BZ2 to OPN_TMP_FILE_$OPN_VM_IMAGE_DISK_FORMAT

# Echo
echo "ECHO .> Extracting..."

# Extract OPN_TMP_FILE_BZ2 to OPN_TMP_FILE_$OPN_ISO_IMAGE_DISK_FORMAT
ORIGIN_ROOT_PATH=$(pwd)
cd $OPN_TMP_DIRECTORY
time bzip2 -d $OPN_TMP_FILE_BZ2
cd $ORIGIN_ROOT_PATH

# Set OPN TMP FILE vars
OPN_TMP_FILE_ISO=$OPN_TMP_DIRECTORY/OPNsense-$OPN_ISO_IMAGE_VERSION-$OPN_ISO_IMAGE_CONSOLE-$OPN_ISO_IMAGE_ARCH.iso

# Echo
echo "ECHO .> $OPN_TMP_FILE_ISO Extracted!"