#!/bin/bash

#### VPC BASTIONS

# ### EU - Italy

# ## VPC BASTION 1 - MIL
# VPC_REGION_NAME=MIL
# echo "DEPLOYING BASTION IN $VPC_REGION_NAME ..."
# scripts/oscVPC-deployBastion-mil.sh
# echo "\!/ CHECK IF THE BASTION WAS DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

# ### EU - Germany

# ## VPC BASTION 2 - LIM
# VPC_REGION_NAME=LIM
# echo "DEPLOYING BASTION IN $VPC_REGION_NAME ..."
# scripts/oscVPC-deployBastion-lim.sh
# echo "\!/ CHECK IF THE BASTION WAS DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

### EU - France

# ## VPC BASTION 3 - GRA
# VPC_REGION_NAME=GRA
# echo "DEPLOYING BASTION IN $VPC_REGION_NAME ..."
# scripts/oscVPC-deployBastion-gra.sh
# echo "\!/ CHECK IF THE BASTION WAS DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

## VPC BASTION 4 - PAR
VPC_REGION_NAME=PAR
VPC_OPN_NODE_ID=1
VPC_ZONE=eu-west-par-a
echo "DEPLOYING OPNSENSE node$VPC_OPN_NODE_I IN $VPC_REGION_NAME on $VPC_ZONE zone"
scripts/oscVPC-deployOPN-par.sh $VPC_OPN_NODE_ID $VPC_ZONE
echo "\!/ CHECK IF OPNSENSE WAS DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"
VPC_OPN_NODE_ID=2
VPC_ZONE=eu-west-par-b
echo "DEPLOYING OPNSENSE node$VPC_OPN_NODE_I IN $VPC_REGION_NAME on $VPC_ZONE zone"
scripts/oscVPC-deployOPN-par.sh $VPC_OPN_NODE_ID $VPC_ZONE
echo "\!/ CHECK IF OPNSENSE WAS DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"
