#!/bin/bash

### VPC NETS

## VPC NET 1 - LIM
VPC_REGION_NAME=LIM
echo "DEPLOYING NETWORK IN $VPC_REGION_NAME ..."
scripts/oscVPC-deployNetwork-lim.sh
echo "\!/ CHECK THE NETWORK IF DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

# VPC NET 2 - GRA
VPC_REGION_NAME=GRA
echo "DEPLOYING NETWORK IN $VPC_REGION_NAME ..."
scripts/oscVPC-deployNetwork-gra.sh
echo "\!/ CHECK THE NETWORK IF DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

## VPC NET 3 - MIL
# VPC_REGION_NAME=MIL
# echo "DEPLOYING NETWORK IN $VPC_REGION_NAME ..."
# scripts/oscVPC-deployNetwork-mil.sh
# echo "\!/ CHECK THE NETWORK IF DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"

## VPC NET 4 - PAR
VPC_REGION_NAME=PAR
echo "DEPLOYING NETWORK IN $VPC_REGION_NAME ..."
scripts/oscVPC-deployNetwork-par.sh
echo "\!/ CHECK THE NETWORK IF DEPLOYED IN $VPC_REGION_NAME SUCCESSFUL \!/"